default:
  seed: 356

dataset:
  path: data
  data: adult_data
  format: csv

target:
  name: income
  neg_class: 0
  pos_class: 1

features:
  drop_features: ["x", "fnlwgt", "educational-num"]
  scale_method: standardization

modelling:
  train_test_sample:
    test_size: 0.25
    random_seed: 123
  ohe_task:
    drop_first: true
  training_process:
    n_splits: 10
    n_repeats: 2
    n_jobs: -1
  model_type: "random_forest"
  hyperparameters:
    logistic:
      max_iter: 1000
    random_forest:
      criterion: gini
      min_samples_split: 5
      n_estimators: [6, 8, 10, 12]
      max_depth: [2, 4]
  metric: "accuracy"
  threshold: 0.3

mlflow_register:
  experiment_id: "705325428535656634"
  path_model_name: "uned_model"
  registered_model_name: "uned_tutorial_model"
  path_scale_name: "uned_scale"
  registered_scale_name: "uned_tutorial_scale"
